#!/bin/bash

#/ NAME
#/     aoh-stub -- stuff for anchoring alpha_omega deploy helpers to aoh-
#/

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_treadstone"

# entry point
function main {
  local app_ruby="$(ryaml $shome/config/deploy.yml app_ruby)"
  local ruby_loader="$(ryaml $shome/config/deploy.yml ruby_loader)"
  PATH="$PATH:/usr/local/rvm/bin:$HOME/.rvm/bin"

  if ! $ruby_loader $app_ruby bundle check 2>&- > /dev/null; then
    $ruby_loader $app_ruby bundle install --local --quiet
  fi
  $ruby_loader $app_ruby bundle exec ao "${BASH_SOURCE##*/}" "$@"
}

main "$@"
