#!/bin/bash

#/ NAME
#/     bundle-ruby -- bundle release with bundler and rvm
#/
#/ SYNOPSIS
#/     
#/     bundle-ruby ruby_loader ruby bundler_options


# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function main {
    bundle exec vagrant up || bundle exec vagrant provision
}

require sub "$BASH_SOURCE" "$@"
